import type { Metadata } from "next";
import { Noto_Serif_JP } from "next/font/google";
import "./globals.css";

const NoteSerifJP = Noto_Serif_JP({
  subsets: ["latin"], // 必要なサブセットを指定します
  weight: ["400", "700"], // 使用するフォントウェイトを指定
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className="dark">
      <body className={NoteSerifJP.className}>{children}</body>
    </html>
  );
}
